#ifndef	_FINGERPRINTCONFIG_H_
#define	_FINGERPRINTCONFIG_H_


#define	_FINGERPRINT_USART						huart2
#define	_FINGERPRINT_POWER_GPIO				GPIOC
#define	_FINGERPRINT_POWER_PIN				GPIO_PIN_9
#define	_FINGERPRINT_IRQ_GPIO					GPIOC
#define	_FINGERPRINT_IRQ_PIN					GPIO_PIN_8


#endif
